ignore string written to tmp file

diff --git a/backup_to_external_hd b/backup_to_external_hd
--- a/backup_to_external_hd
+++ b/backup_to_external_hd
@@ -22,7 +22,7 @@ DESTINATION=/mnt/ext_hd/backup/data/
 
 #rsync everything
 echo "Starting backup of /home/data"
-( rsync -ar$DEBUG_FLAG $SOURCE $DESTINATION && echo "Successfully backuped data" ) || echo "Couldn't successfully backup home directory"	
+( rsync -ar$DEBUG_FLAG $SOURCE $DESTINATION && echo "Successfully backuped data" ) || echo "Couldn't successfully backup data directory"	
 
 #HOME DRIVE
 #define source and target for 
@@ -35,9 +35,11 @@ DESTINATION=/mnt/ext_hd/backup/home/
 [ -d $DESTINATION ] && mkdir -p $DESTINATION
  
 #There's quite a bit of uninteresting stuff that we need to ignore
-declare -a IGNORE=( .conda .mozilla Downloads .thunderbird .rstudio-desktop .pki .matlab .local .jupyter .java .ipython .conda .cache "cmdstan-2.23.0" Zotero .zotero "MATLAB Add-Ons" .vscode-oss .vnc .vim .pylint .npm .gnupg .fltk .cargo)
-IGNORE_STRING=$( printf -- "--exclude %s " ${IGNORE[@]} )
+declare -a IGNORE=( "'*.pic'" .conda .mozilla Downloads .thunderbird .rstudio-desktop .pki .matlab .local .jupyter .java .ipython .conda .cache "cmdstan-2.24.1" "cmdstan-2.23.0" Zotero .zotero MATLAB "'MATLAB Add-Ons'" .vscode-oss .vnc .vim .pylint .npm .gnupg .fltk .cargo.zoom )
+
+#print to tmp-file. No idea why that doesn't work in a string
+printf "%s\n" ${IGNORE[@]} > /tmp/ignore.txt
 
 #rsync everything but annyoing amounts of .-directories
 echo "Starting backup of home directory" 
-(rsync -ar$DEBUG_FLAG $IGNORE_STRING $SOURCE $DESTINATION && echo "Successfully backuped home dir") || echo "Couldn't successfully backup home directory"	
+(rsync -ar$DEBUG_FLAG --no-links --exclude-from=/tmp/ignore.txt $SOURCE $DESTINATION && echo "Successfully backuped home dir") || echo "Couldn't successfully backup home directory"	
